import type { Metadata } from 'next';
import { Inter, Indie_Flower } from 'next/font/google';
import '@/styles/globals.css';
import './page.css';
import Footer from '@/components/Footer';

const interFont = Inter({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-inter',
});

const indieFlower = Indie_Flower({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400'],
  variable: '--font-indie',
});

export const metadata: Metadata = {
  title: 'Domo Challenge',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${interFont.variable} ${indieFlower.variable} bg-white min-vh-100 mw-100 overflow-x-hidden`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
